#
# *************************************************
# Copyright (c) 2019, Grindrod Bank Limited
# License MIT: https://opensource.org/licenses/MIT
# **************************************************
#

version: '3'
services:
  
  keycloak:
    image: "jboss/keycloak:4.7.0.Final"
    ports:
     - "9191:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/tmp/tilkynna-realm.json"
    volumes:
      - ./tilkynna-realm.json:/tmp/tilkynna-realm.json
  sftp:
    image: atmoz/sftp:alpine
    ports:
        - "2222:22"
    command: foo:pass:::upload
